### ISSUE TITLE
[BUG] Imgur Albums on Reddit user page.

### ISSUE THREAD

**Issue by twosushi** [AAndyProgram/SCrawler#100]
Does not download Imgur albums from a NSFW Reddit user page. Not sure if this is intended behavior.

1. <details><summary>NSFW URL</summary>
    <pre>
    https://www.reddit.com/user/Ok_wat/
    </pre>
   </details>
2. Add link to SCrawler, Use "Download data".
3. Only downloads some Imgur posts but not the albums.

Please advise,
Thanks.

**Comment by AAndyProgram** [comment]
Confirmed. I need time to figure out what happened. Previously, imgur albums could also be downloaded.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by twosushi** [comment]
Sorry to be a bother but it seems for me both 
SCrawler_2023.1.24.0_x64.zip &
SCrawler_2023.1.24.0_x86.zip 
releases still can't seem to download the Imgur albums.

All I do is download release, extract release, open extracted Scrawler, add link, right click "Download Data". 
I seem to still only be getting the same 11 images from the link as last time.
Or maybe I'm doing something wrong.

Please advise,
Thanks again for your time.

**Comment by AAndyProgram** [comment]
I have completely downloaded the profile you posted. Have you set up an [Imgur client ID](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-imgur-client-id)?

An Imgur client ID is required to download NSFW content. Otherwise, if an image, posted on Reddit as an image (like https://imgur.com/abcde.jpg) will be try to download using the regular algorithm. URLs like https://imgur.com/abcde require an Imgur client ID.

**Comment by twosushi** [comment]
You are correct. I did not know I needed to add the Imgur Client ID. I have since added it and it has fixed my issue. 
Thank you very much!

**Comment by AAndyProgram** [comment]
You are welcome 😊

**Comment by twosushi** [comment]
Hmm, I have an actual bug this time with some of the Imgur albums still.
So it handles the rest fine. But when Imgur URL has one with a "#" symbol in it it seems to not pick it up.
Still the same Reddit user link. 

For the following posts:

My New [F]ancy Teddy! ;) 
https://imgur.com/a/UMJkw#ZyxWikW

{F} Any <3 for Librarians?
https://imgur.com/a/YlRLj#bEuCbES

(F) Who's ready for dessert? {part 2}
https://imgur.com/a/LtLxW#0

(F)or All The Good Boys And Girls: Dessert {part 3}
https://imgur.com/a/6olDN#0

They seem to either not be detected/not downloaded. I'm not sure which.
Hopefully you can replicate the bug.
If I am missing something again please let me know.

Sorry for all fuss. It's not urgent, just whenever you have time to look at it.
Thanks again!

**Comment by AAndyProgram** [comment]
Confirmed. I'll fix it tomorrow.

**Comment by AAndyProgram** [comment]
Fixed (I decided to fix it today😊). Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

Thank you for providing problematic links and for such detailed information. Hope everything goes well this time.

>Sorry for all fuss. It's not urgent, just whenever you have time to look at it.

Please feel free to ask questions and post problems.

**Comment by AAndyProgram** [comment]
Is everything okay this time?

**Comment by twosushi** [comment]
> Is everything okay this time?

Yes, it's all fixed. I will close the thread as well. Thanks!
