### ISSUE TITLE
[BUG] Photo galleries from PornHub are not downloading

### ISSUE THREAD

**Issue by blackgur** [AAndyProgram/SCrawler#115]
**Describe the bug**
Photo galleries from PH are not downloading.

**To Reproduce**
1. **Profile URL**: https://www.pornhub.com/model/sa-shulya-slut
2. Whether or not "Download photos only from modelhub" is checked is irrelevant.
With the checkbox unchecked, the program only creates a folder with the name of the photo album but does not download photos.
3. The only thing in the log is "Some posts didn't download. You can see them in the 'Missing posts' form.". 
But the missing posts are empty.
![SCrawler_FaAv2h2AP0](https://user-images.githubusercontent.com/6291267/226750026-9d7e3c42-8406-4b37-912b-269125ca3914.png)
 
**Release information (please complete the following information):**
 - Win11
 - x64
 - 2023.3.5.0

**Comment by AAndyProgram** [comment]
I need time to find out what happened. I think it might be because PornHub redirects to ModelHub for her albums, but ModelHub is showing 404 error (https://www.modelhub.com/sa-shulya-slut/photos).

**Comment by AAndyProgram** [comment]
Will be fixed in the next version. You will need to uncheck `Download photo only from ModelHub`.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Comment by blackgur** [comment]
After updating the app still does not download photos.
Checkbox «Download photo only from ModelHub» removed for users who have 404 error on modelhub.

**Comment by AAndyProgram** [comment]
Hm... Interesting... Try to remove this profile from SCrawler and add it again with `Download photo only from ModelHub` unchecked.

**Comment by AAndyProgram** [comment]
I swear I tested this profile and everything was processed. The only thing I can guess is that the profile is already linked to the ModelHub downloader function.

**Comment by AAndyProgram** [comment]
You can also try changing the `PhotoPageModel` parameter in the user's settings file (in the user's settings path) to 0 (zero). Then restart SCrawler

**Comment by AAndyProgram** [comment]
Setting `PhotoPageModel` to `0` tells SCrawler to detect the page type again.
PornHub value is `1`
ModelHub value is `2`

https://github.com/AAndyProgram/SCrawler/blob/b2a9b224780d969103ce7eebf541c49ec4253428/SCrawler/API/PornHub/UserData.vb#L90-L94

**Comment by AAndyProgram** [comment]
Have you tried? Please feel free to message me on Discord or Matrix.

**Comment by blackgur** [comment]
I tried deleting these users - didn't help. 
I tried changing the variables in user settings - did not help.
I deleted them in the application + settings folder - didn't help.

When I have time I will try to download these users using a clean client.

**Comment by AAndyProgram** [comment]
![image](https://user-images.githubusercontent.com/88590076/235362959-418727d8-11fd-4aee-9fe6-072da5640732.png)

**Comment by AAndyProgram** [comment]
Are you sure that "Download images" is checked in this user's settings?

**Comment by blackgur** [comment]
I don't know. Even from a clean client with the checkbox unchecked, the photos are not downloaded.
![image](https://user-images.githubusercontent.com/6291267/235527504-9bb797b1-2853-4e0b-aa69-fef987c3ec24.png)

**Comment by blackgur** [comment]
> Are you sure that "Download images" is checked in this user's settings?

Yeah, im sure
![image](https://user-images.githubusercontent.com/6291267/235528126-28ddfb2a-0da3-45ed-858e-87e8a9cf5167.png)

**Comment by AAndyProgram** [comment]
Try adding cookies. Even if it doesn't work, I can't help, sorry.

**Comment by blackgur** [comment]
Cookies don't help either.
🤷‍♂️

**Comment by AAndyProgram** [comment]
Sorry, I don't know what's going on. I can download it. You've seen the screenshot.

**Comment by blackgur** [comment]
I believe you. It's just not clear why I can't do it.
I don't have any restrictions from the state on this site.

**Comment by AAndyProgram** [comment]
Where are you from? Maybe you can try to download via VPN?

**Comment by blackgur** [comment]
Central Asia.
But private VPN didn't help either

**Comment by blackgur** [comment]
Do you have any mechanism for getting more detailed logs than you have now?

**Comment by AAndyProgram** [comment]
>Central Asia.
>But private VPN didn't help either

Oh, sure, Cyrillic encoding. If you mean Russia, one guy from Russia told me last year that he can't download some posts, but he can see them and I can download them. The problem was solved through VPN. However, you say the VPN doesn't work.

>Do you have any mechanism for getting more detailed logs than you have now?

Unfortunately no.

I've tested a clean install and confirm that without cookies, I can't download that person's albums either. Once I added the cookies, I downloaded all the photos.
I'm attaching the settings for test. What should you do:
1. Create a new folder and unpack SCrawler into it
2. Unpack this archive into it too
3. Launch SCrawler
4. Open your PornHub settings and [add cookies](https://github.com/AAndyProgram/SCrawler/wiki/Settings#first-method)
5. Make sure the VPN is on
6. Click download

[TestSettings.zip](https://github.com/AAndyProgram/SCrawler/files/11371387/TestSettings.zip)

**Comment by blackgur** [comment]
No, not Russia. But I use Cyrillic encoding.
Test settings didn't help - with or without VPN.

**Comment by AAndyProgram** [comment]
Sorry. I don't know what to say. I tried my best.

**Comment by blackgur** [comment]
At the same time profiles that have photos on modelhub download without any problems.
Strange.
