### ISSUE TITLE
[BUG] instagram Hash not able to be auto-filled from cookies

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#52]
I have a suspicion that this is due to instagram changing something on their end again.

I got an error with my instagram credentials, but when I went to update them, the Hash field wouldn't fill itself out when the button (circled below) was clicked (in the past I've done this many times across many versions without any issue)

From latest version (fresh install) to clarify exactly what I mean.
![image](https://user-images.githubusercontent.com/100350754/171737003-790b9439-4483-4c4b-a822-44bcbfc72a37.png)

I tried using cookies from a different account, and I tried on a fresh install and some past versions, and all had the same issue.

I'm not familiar enough with the ins-and-outs of instagram credentials to know how to manually locate my Hash unfortunately, so I haven't been able to try that

**Comment by AAndyProgram** [comment]
**Confirmed** 😞 

>I have a suspicion that this is due to instagram changing something on their end again.

It is.

The best I can do for you right now is just a regular expression: ```regeneratorRuntime.+?function.+?var h="([\d\w\S]+?)"```

1. Open new tab page
1. Open dev tools
1. Go to ```instagram.com```
1. The dev tools must display the ```www.instagram.com``` document
1. Go to dev tools
1. Press ```Ctrl``` + ```F```
1. Click ```.*``` and paste the regular expression. Then press enter
1. Click document by document and in the open response press ```Ctrl``` + ```F``` and paste the regular expression. Search until you find an alphanumeric text of length ~**32**

**Comment by AAndyProgram** [comment]
I'll post a new release in a few days. I added automation and cool toast notifications from automation. So unfortunately, SCrawler may not work on windows 7 and 8. What operating system are you using?

**Comment by TGJ64** [comment]
I'm on Windows 10 thankfully

**Comment by AAndyProgram** [comment]
Did you find the hash with regex I posted?

**Comment by AAndyProgram** [comment]
BTW, did you like SCrawler on [this site](https://alternativeto.net/software/scrawler/about/)

**Comment by TGJ64** [comment]
> Did you find the hash with regex I posted?

I think I did find it following your instructions,
I found two different alphanumeric strings while searching through, one of which was the same hash as was still stored in an older version of SCrawler (I assumed my hash had changed but maybe not), but I still get an instagram credentials error using either, so I'm no longer sure what the issue is, since I'm able to update everything else manually just fine. 
Going to leave it until next version since I'm not needing to use it for a bit anyhow and whatever strange issue I'm having may just end up being resolved with your changes.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by TGJ64** [comment]
> If you have entered valid credentials and are still getting an error, you must post the **profile URL** and log. Without the profile URL I can't identify the error!

sorry it took me so long to reply to this, I haven't tried using it for a week. The new update properly grabs the Hash but I still don't seem to have resolved the issue with credentials. After it didn't work on either of my two accounts, I made a new instagram account to test it out and a fresh install of SCrawler v2022.6.6.0, then did the following steps for instagram credentials:

- Copied cookies from Application tab and added cookies using "From Google Chrome".
- Selected 🔁 button to automatically load Hash value
- Opened Network tab and loaded instagram Saved photos page
- Copied and added values for "x-csrftoken, "x-ig-app-id" and "x-ig-www-claim" 

I did not add Hash 2 or Saved posts user, as I've never previously needed to and my understanding is they're only needed if I want to save my own "Saved Posts".
I also have not installed any of the plugins. None of these have previously prevented me from downloading from instagram (though they always give me errors in the log when I first run).

The new account I tested this with is tgj64_ 
Here is the log from my test (using emmawatson as the test User), let me know if there's anything I should try:

>2022-06-10 06:29:16: [PluginHost.New]
	Could not load file or assembly 'SCrawler.Plugin.LPSG, Version=2022.6.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2022-06-10 06:29:16: Message: Could not load file or assembly 'SCrawler.Plugin.LPSG, Version=2022.6.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
	HelpLink: 
	StackTrace:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
	   at SCrawler.Plugin.Hosts.PluginHost..ctor(SFile AssemblyFile, XmlFile& _XML, SFile GlobalPath, XMLValue`1& _Temp, XMLValue`1& _Imgs, XMLValue`1& _Vids)
>	-----InnerException 1-----
	
>	-----InnerException 2-----
	Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
	HelpLink: 
	StackTrace: 
2022-06-10 06:29:16: [PluginHost.New]
	Could not load file or assembly 'SCrawler.Plugin.XVIDEOS, Version=2022.6.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2022-06-10 06:29:16: Message: Could not load file or assembly 'SCrawler.Plugin.XVIDEOS, Version=2022.6.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
	HelpLink: 
	StackTrace:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
	   at SCrawler.Plugin.Hosts.PluginHost..ctor(SFile AssemblyFile, XmlFile& _XML, SFile GlobalPath, XMLValue`1& _Temp, XMLValue`1& _Imgs, XMLValue`1& _Vids)
>	-----InnerException 1-----
	
>	-----InnerException 2-----
	Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
	HelpLink: 
	StackTrace: 
2022-06-10 06:38:51: Instagram - emmawatson: get Instagram user id
	Invalid JSON primitive: for.
2022-06-10 06:38:51: Message: Invalid JSON primitive: for.
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Tools.WebDocuments.JSON.JsonDocument.Parse(String Text, String RootNodeName, ErrorsDescriber e)
	   at PersonalUtilities.Tools.WebDocuments.JSON.JsonDocument.Parse(String Text, ErrorsDescriber e)
	   at SCrawler.API.Instagram.UserData.GetUserId()
2022-06-10 06:38:51: Instagram hash requested: emmawatson [Timeline]
2022-06-10 06:38:51: Instagram - emmawatson: data downloading error []
	User ID is not detected
	Parameter name: ID
2022-06-10 06:38:51: Message: User ID is not detected
	Parameter name: ID
	HelpLink: 
	StackTrace:    at SCrawler.API.Instagram.UserData.DownloadData(String Cursor, Sections Section, CancellationToken Token)
2022-06-10 06:38:51: Instagram - emmawatson: get Instagram user id
	Invalid JSON primitive: for.
2022-06-10 06:38:51: Message: Invalid JSON primitive: for.
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Tools.WebDocuments.JSON.JsonDocument.Parse(String Text, String RootNodeName, ErrorsDescriber e)
	   at PersonalUtilities.Tools.WebDocuments.JSON.JsonDocument.Parse(String Text, ErrorsDescriber e)
	   at SCrawler.API.Instagram.UserData.GetUserId()
2022-06-10 06:38:51: Instagram hash requested: emmawatson [Stories]
2022-06-10 06:38:51: Instagram - emmawatson: data downloading error []
	User ID is not detected
	Parameter name: ID
2022-06-10 06:38:51: Message: User ID is not detected
	Parameter name: ID
	HelpLink: 
	StackTrace:    at SCrawler.API.Instagram.UserData.DownloadData(String Cursor, Sections Section, CancellationToken Token)
2022-06-10 06:38:52: Check your Instagram credentials

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

And please start writing me answers when I fix your issues. A few words are enough (like "everything is fine now").

**Comment by AAndyProgram** [comment]
>fresh install of SCrawler v2022.6.6.0

BTW, a fresh install doesn't fix anything. SCrawler doesn't store errors or anything that allows it to skip some functions etc. You're just making it harder to work with SCrawler because after a fresh install you'll have to add and download profiles again. If I change some SCrawler settings, I always make the methods compatible with older versions. And I leave them in SCrawler for at least 5 versions. This simplifies the user experience as they don't need to update settings (except when I write it in the release notes). If you need to update your credentials, just open the site settings and change them.

**Comment by TGJ64** [comment]
> And please start writing me answers when I fix your issues. A few words are enough (like "everything is fine now").

I usually try to! Sometimes I just don't get around to trying the changes for a week or so. The latest version fixed my issues, thanks!

**Comment by AAndyProgram** [comment]
And thank you. Your issues help me make SCrawler better. As far as I can see, you are one of the most active users of SCrawler. I really appreciate it and I'm very glad that you like my program! 😊

**Comment by AAndyProgram** [comment]
Instagram has changed something again. But now we have the ability (which we didn't have before) to get a **Hash** in the same way as [Hash2](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-instagram-hash-2).

1. Open browser developer tools
1. Go to Network
1. If this tab contain any data, clear it.
1. **Open any profile**.
1. Click Ctrl + F and find the text query_hash=. The alphanumeric value after the equal sign is the required hash.
Copy this and paste it into the Hash 2 field on the Instagram settings form.

**Comment by TGJ64** [comment]
> Curved arrows now don't work (return wrong hash). They will be removed in the next version.

Related to this change with the new Hash issues, I'm finding that when I Download All (and also occasionally some other times, I've not nailed down what causes it exactly) the hash field gets automatically re-filled with the wrong hash as well. I'm assuming there may be some points in your code where it tries to refresh the hash automatically but I'm generally having to confirm it's using the proper hash and then select everything and Download Selected or else the hash gets changed again.

**Comment by AAndyProgram** [comment]
Yes, it is. The problem is in SCrawler. This will be fixed in the next version
